# Generated by Django 5.2.10 on 2026-02-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/images/'),
        ),
    ]
