# Generated by Django 5.2.10 on 2026-02-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
