# Generated by Django 5.2.10 on 2026-02-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_payment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
